export const stateWithDistrict = {
  "andhra pradesh": [
    "alluri sitharama raju",
    "anakapalli",
    "ananthapuram",
    "annamayya",
    "bapatla",
    "chittoor",
    "dr. b.r. ambedkar konaseema",
    "east godavari",
    "eluru",
    "guntur",
    "kakinada",
    "krishna",
    "kurnool",
    "nandyal",
    "Sri Potti Sriramulu Nellore",
    "ntr",
    "palnadu",
    "parvathipuram manyam",
    "prakasam",
    "sri sathya sai",
    "srikakulam",
    "tirupati",
    "visakhapatnam",
    "vizianagaram",
    "west godavari",
    "ysr kadapa",
  ],
  "arunachal pradesh": [
    "tawang",
    "west kameng",
    "east kameng",
    "papum pare",
    "kurung kumey",
    "kra daadi",
    "lower subansiri",
    "upper subansiri",
    "west siang",
    "east siang",
    "siang",
    "upper siang",
    "lower dibang valley",
    "dibang valley",
    "anjaw",
    "lohit",
    "namsai",
    "changlang",
    "tirap",
    "longding",
  ],
  assam: [
    "baksa",
    "barpeta",
    "biswanath",
    "bongaigaon",
    "cachar",
    "charaideo",
    "chirang",
    "darrang",
    "dhemaji",
    "dhubri",
    "dibrugarh",
    "goalpara",
    "golaghat",
    "hailakandi",
    "hojai",
    "jorhat",
    "kamrup",
    "kamrup metropolitan",
    "karbi anglong",
    "karimganj",
    "kokrajhar",
    "lakhimpur",
    "majuli",
    "morigaon",
    "nagaon",
    "nalbari",
    "dima hasao",
    "sivasagar",
    "sonitpur",
    "south salmara-mankachar",
    "tinsukia",
    "udalguri",
    "west karbi anglong",
  ],
  bihar: [
    "araria",
    "arwal",
    "aurangabad",
    "banka",
    "begusarai",
    "bhagalpur",
    "bhojpur",
    "buxar",
    "darbhanga",
    "east champaran",
    "gaya",
    "gopalganj",
    "jamui",
    "jehanabad",
    "kaimur",
    "katihar",
    "khagaria",
    "kishanganj",
    "lakhisarai",
    "madhepura",
    "madhubani",
    "munger",
    "muzaffarpur",
    "nalanda",
    "nawada",
    "patna",
    "purnia",
    "rohtas",
    "saharsa",
    "samastipur",
    "saran",
    "sheikhpura",
    "sheohar",
    "sitamarhi",
    "siwan",
    "supaul",
    "vaishali",
    "west champaran",
  ],
  chhattisgarh: [
    "balod",
    "baloda bazar",
    "balrampur",
    "bastar",
    "bemetara",
    "bijapur",
    "bilaspur",
    "dantewada",
    "dhamtari",
    "durg",
    "gariaband",
    "gaurela-pendra-marwahi",
    "janjgir-champa",
    "jashpur",
    "kabirdham",
    "kanker",
    "khairagarh-chhuikhadan-gandai",
    "kondagaon",
    "korba",
    "koriya",
    "mahasamund",
    "manendragarh-chirmiri-bharatpur",
    "mohla-manpur-ambagarh chowki",
    "mungeli",
    "narayanpur",
    "raigarh",
    "raipur",
    "rajnandgaon",
    "sakti",
    "sarangarh-bilaigarh",
    "sarguja",
    "sujapur",
    "surajpur",
  ],
  goa: ["north goa", "south goa"],
  gujarat: [
    "ahmedabad",
    "amreli",
    "anand",
    "aravalli",
    "banaskantha",
    "bharuch",
    "bhavnagar",
    "botad",
    "chhota udaipur",
    "dahod",
    "dang",
    "devbhoomi dwarka",
    "gandhinagar",
    "gir somnath",
    "jamnagar",
    "junagadh",
    "kheda",
    "kutch",
    "mahisagar",
    "mehsana",
    "morbi",
    "narmada",
    "navsari",
    "panchmahal",
    "patan",
    "porbandar",
    "rajkot",
    "sabarkantha",
    "surat",
    "surendranagar",
    "tapi",
    "vadodara",
    "valsad",
  ],
  haryana: [
    "ambala",
    "bhiwani",
    "charkhi dadri",
    "faridabad",
    "fatehabad",
    "gurugram",
    "hisar",
    "jhajjar",
    "jind",
    "kaithal",
    "karnal",
    "kurukshetra",
    "mahendragarh",
    "nuh",
    "palwal",
    "panchkula",
    "panipat",
    "rewari",
    "rohtak",
    "sirsa",
    "sonipat",
    "yamunanagar",
  ],
  "himachal pradesh": [
    "bilaspur",
    "chamba",
    "hamirpur",
    "kangra",
    "kinnaur",
    "kullu",
    "lahaul and spiti",
    "mandi",
    "shimla",
    "sirmaur",
    "solan",
    "una",
  ],
  jharkhand: [
    "bokaro",
    "chatra",
    "deoghar",
    "dhanbad",
    "dumka",
    "east singhbhum",
    "garhwa",
    "giridih",
    "godda",
    "gumla",
    "hazaribagh",
    "jamtara",
    "khunti",
    "koderma",
    "latehar",
    "lohardaga",
    "pakur",
    "palamu",
    "ramgarh",
    "ranchi",
    "sahibganj",
    "seraikela kharsawan",
    "simdega",
    "west singhbhum",
  ],
  karnataka: [
    "bagalkot",
    "ballari",
    "belagavi",
    "bengaluru rural",
    "bengaluru urban",
    "bidar",
    "chamarajanagar",
    "chikkaballapur",
    "chikkamagaluru",
    "chitradurga",
    "dakshina kannada",
    "davanagere",
    "dharwad",
    "gadag",
    "hassan",
    "haveri",
    "kalaburagi",
    "kodagu",
    "kolar",
    "koppal",
    "mandya",
    "mysuru",
    "raichur",
    "ramanagara",
    "shivamogga",
    "tumakuru",
    "udupi",
    "uttara kannada",
    "vijayapura",
    "yadgir",
  ],
  kerala: [
    "alappuzha",
    "ernakulam",
    "idukki",
    "kannur",
    "kasaragod",
    "kollam",
    "kottayam",
    "kozhikode",
    "malappuram",
    "palakkad",
    "pathanamthitta",
    "thiruvananthapuram",
    "thrissur",
    "wayanad",
  ],
  "madhya pradesh": [
    "agar malwa",
    "alirajpur",
    "anuppur",
    "ashoknagar",
    "balaghat",
    "barwani",
    "betul",
    "bhind",
    "bhopal",
    "burhanpur",
    "chhatarpur",
    "chhindwara",
    "damoh",
    "datia",
    "dewas",
    "dhar",
    "dindori",
    "guna",
    "gwalior",
    "harda",
    "hoshangabad",
    "indore",
    "jabalpur",
    "jhabua",
    "katni",
    "khandwa",
    "khargone",
    "mandla",
    "mandsaur",
    "morena",
    "narsinghpur",
    "neemuch",
    "niwari",
    "panna",
    "raisen",
    "rajgarh",
    "ratlam",
    "rewa",
    "sagar",
    "satna",
    "sehore",
    "seoni",
    "shahdol",
    "shajapur",
    "sheopur",
    "shivpuri",
    "sidhi",
    "singrauli",
    "tikamgarh",
    "ujjain",
    "umaria",
    "vidisha",
  ],
  maharashtra: [
    "ahmednagar",
    "akola",
    "amravati",
    "aurangabad",
    "beed",
    "bhandara",
    "buldhana",
    "chandrapur",
    "dhule",
    "gadchiroli",
    "gondia",
    "hingoli",
    "jalgaon",
    "jalna",
    "kolhapur",
    "latur",
    "mumbai city",
    "mumbai suburban",
    "nagpur",
    "nanded",
    "nandurbar",
    "nashik",
    "osmanabad",
    "palghar",
    "parbhani",
    "pune",
    "raigad",
    "ratnagiri",
    "sangli",
    "satara",
    "sindhudurg",
    "solapur",
    "thane",
    "wardha",
    "washim",
    "yavatmal",
  ],
  manipur: [
    "bishnupur",
    "chandel",
    "churachandpur",
    "imphal east",
    "imphal west",
    "jiribam",
    "kakching",
    "kamjong",
    "kangpokpi",
    "noney",
    "pherzawl",
    "senapati",
    "tamenglong",
    "tengnoupal",
    "thoubal",
    "ukhrul",
  ],
  meghalaya: [
    "east garo hills",
    "east jaintia hills",
    "east khasi hills",
    "north garo hills",
    "ri bhoi",
    "south garo hills",
    "south west garo hills",
    "south west khasi hills",
    "west garo hills",
    "west jaintia hills",
    "west khasi hills",
  ],
  mizoram: [
    "aizawl",
    "champhai",
    "hnahthial",
    "khawzawl",
    "kolasib",
    "lawngtlai",
    "lunglei",
    "mamit",
    "saitual",
    "serchhip",
  ],
  nagaland: [
    "chümoukedima",
    "dimapur",
    "kiphire",
    "kohima",
    "longleng",
    "mokokchung",
    "mon",
    "noklak",
    "peren",
    "phek",
    "tuensang",
    "wokha",
    "zünheboto",
  ],
  odisha: [
    "angul",
    "balangir",
    "balasore",
    "bargarh",
    "bhadrak",
    "boudh",
    "cuttack",
    "debagarh",
    "dhenkanal",
    "gajapati",
    "ganjam",
    "jagatsinghpur",
    "jajpur",
    "jharsuguda",
    "kalahandi",
    "kandhamal",
    "kendrapara",
    "kendujhar",
    "khordha",
    "koraput",
    "malkangiri",
    "mayurbhanj",
    "nabarangpur",
    "nayagarh",
    "nuapada",
    "puri",
    "rayagada",
    "sambalpur",
    "subarnapur",
    "sundargarh",
  ],
  punjab: [
    "amritsar",
    "barnala",
    "bathinda",
    "faridkot",
    "fatehgarh sahib",
    "fazilka",
    "ferozepur",
    "gurdaspur",
    "hoshiarpur",
    "jalandhar",
    "kapurthala",
    "ludhiana",
    "malerkotla",
    "mansa",
    "moga",
    "muktsar",
    "pathankot",
    "patiala",
    "rupnagar",
    "sahibzada ajit singh nagar",
    "sangrur",
    "shaheed bhagat singh nagar",
    "tarn taran",
  ],
  rajasthan: [
    "ajmer",
    "alwar",
    "banswara",
    "baran",
    "barmer",
    "bharatpur",
    "bhilwara",
    "bikaner",
    "bundi",
    "chittorgarh",
    "churu",
    "dausa",
    "dholpur",
    "dungarpur",
    "hanumangarh",
    "jaipur",
    "jaisalmer",
    "jalore",
    "jhalawar",
    "jhunjhunu",
    "jodhpur",
    "karauli",
    "kota",
    "nagaur",
    "pali",
    "pratapgarh",
    "rajsamand",
    "sawai madhopur",
    "sikar",
    "sirohi",
    "sri ganganagar",
    "tonk",
    "udaipur",
  ],
  sikkim: ["gangtok", "gyalshing", "mangan", "namchi", "pakyong", "soreng"],
  "tamil nadu": [
    "ariyalur",
    "chengalpattu",
    "chennai",
    "coimbatore",
    "cuddalore",
    "dharmapuri",
    "dindigul",
    "erode",
    "kallakurichi",
    "kanchipuram",
    "kanyakumari",
    "karur",
    "krishnagiri",
    "madurai",
    "nagapattinam",
    "namakkal",
    "nilgiris",
    "perambalur",
    "pudukkottai",
    "ramanathapuram",
    "ranipet",
    "salem",
    "sivaganga",
    "tenkasi",
    "thanjavur",
    "theni",
    "thoothukudi",
    "tiruchirappalli",
    "tirunelveli",
    "tirupathur",
    "tiruppur",
    "tiruvallur",
    "tiruvannamalai",
    "tiruvarur",
    "vellore",
    "viluppuram",
    "virudhunagar",
  ],
  telangana: [
    "adilabad",
    "bhadradri kothagudem",
    "hanamkonda",
    "hyderabad",
    "jagtial",
    "jangaon",
    "jayashankar bhupalapally",
    "jogulamba gadwal",
    "kamareddy",
    "karimnagar",
    "khammam",
    "komaram bheem",
    "mahabubabad",
    "mahabubnagar",
    "mancherial",
    "medak",
    "medchal malkajgiri",
    "mulugu",
    "nagarkurnool",
    "nalgonda",
    "narayanpet",
    "nirmal",
    "nizamabad",
    "peddapalli",
    "rajanna sircilla",
    "ranga reddy",
    "sangareddy",
    "siddipet",
    "suryapet",
    "vikarabad",
    "wanaparthy",
    "warangal",
    "yadadri bhuvanagiri",
  ],
  tripura: [
    "dhalai",
    "gomati",
    "khowai",
    "north tripura",
    "sepahijala",
    "south tripura",
    "unakoti",
    "west tripura",
  ],
  "uttar pradesh": [
    "agra",
    "aligarh",
    "ambedkar nagar",
    "amethi",
    "amroha",
    "auraiya",
    "ayodhya",
    "azamgarh",
    "baghpat",
    "bahraich",
    "ballia",
    "balrampur",
    "banda",
    "barabanki",
    "bareilly",
    "basti",
    "bhadohi",
    "bijnor",
    "budaun",
    "bulandshahr",
    "chandauli",
    "chitrakoot",
    "deoria",
    "etah",
    "etawah",
    "farrukhabad",
    "fatehpur",
    "firozabad",
    "gautam buddha nagar",
    "ghaziabad",
    "ghazipur",
    "gonda",
    "gorakhpur",
    "hamirpur",
    "hapur",
    "hardoi",
    "hathras",
    "jalaun",
    "jaunpur",
    "jhansi",
    "kannauj",
    "kanpur dehat",
    "kanpur nagar",
    "kasganj",
    "kaushambi",
    "kheri",
    "kushinagar",
    "lalitpur",
    "lucknow",
    "maharajganj",
    "mahoba",
    "mainpuri",
    "mathura",
    "mau",
    "meerut",
    "mirzapur",
    "moradabad",
    "muzaffarnagar",
    "pilibhit",
    "pratapgarh",
    "prayagraj",
    "raebareli",
    "rampur",
    "saharanpur",
    "sambhal",
    "sant kabir nagar",
    "shahjahanpur",
    "shamli",
    "sharavasti",
    "siddharthnagar",
    "sitapur",
    "sonbhadra",
    "sultanpur",
    "unnao",
    "varanasi",
  ],
  uttarakhand: [
    "almora",
    "bageshwar",
    "chamoli",
    "champawat",
    "dehradun",
    "haridwar",
    "nainital",
    "pauri garhwal",
    "pithoragarh",
    "rudraprayag",
    "tehri garhwal",
    "udham singh nagar",
    "uttarkashi",
  ],
  "west bengal": [
    "alipurduar",
    "bankura",
    "birbhum",
    "cooch behar",
    "dakshin dinajpur",
    "darjeeling",
    "hooghly",
    "howrah",
    "jalpaiguri",
    "jhargram",
    "kalimpong",
    "kolkata",
    "malda",
    "murshidabad",
    "nadia",
    "north 24 parganas",
    "paschim bardhaman",
    "paschim medinipur",
    "purba bardhaman",
    "purba medinipur",
    "purulia",
    "south 24 parganas",
    "uttar dinajpur",
  ],
  "andaman and nicobar islands": [
    "nicobar",
    "north and middle andaman",
    "south andaman",
  ],
  chandigarh: ["chandigarh"],
  "dadra and nagar haveli and daman and diu": [
    "dadra and nagar haveli",
    "daman",
    "diu",
  ],
  delhi: [
    "central delhi",
    "east delhi",
    "new delhi",
    "north delhi",
    "north east delhi",
    "north west delhi",
    "shahdara",
    "south delhi",
    "south east delhi",
    "south west delhi",
    "west delhi",
  ],
  "jammu kashmir & ladakh": [
    "anantnag",
    "bandipora",
    "baramulla",
    "budgam",
    "doda",
    "ganderbal",
    "jammu",
    "kathua",
    "kishtwar",
    "kulgam",
    "kupwara",
    "poonch",
    "pulwama",
    "rajouri",
    "ramban",
    "reasi",
    "samba",
    "shopian",
    "srinagar",
    "udhampur",
    "kargil",
    "leh",
  ],
  lakshadweep: [
    "agatti",
    "amini",
    "andrott",
    "bitra",
    "chetlat",
    "kavaratti",
    "kadmat",
    "kalpeni",
    "kilthan",
    "minicoy",
  ],
  puducherry: ["karaikal", "mahe", "puducherry", "yanam"],
};
