export const stateWithDistrict = {
  "andaman & nicobar": ["nicobar", "north & middile andaman", "south andaman"],
  "andhra pradesh": [
    "alluri sitharama raju",
    "anakapalli",
    "ananthapuram",
    "annamayya",
    "bapatla",
    "c i d",
    "chittoor",
    "cid1",
    "cid2",
    "coastal security police",
    "east godavari",
    "eluru",
    "grp guntakal",
    "grp vijayawada",
    "guntur",
    "kakinada",
    "konaseema",
    "krishna",
    "kurnool",
    "nandyal",
    "ntr commissionerate",
    "palnadu",
    "parvathipuram manyam",
    "prakasam",
    "red sanders anti-smuggling task force",
    "sri potti sriramulu nellore",
    "sri sathya sai",
    "srikakulam",
    "tirupathi",
    "visakhapatnam commissionerate",
    "vizianagaram",
    "west godavari",
    "ysr",
  ],
  "arunachal pradesh": [
    "anjaw",
    "bichom",
    "changlang",
    "crime branch",
    "dibang valley",
    "kameng east",
    "kameng west",
    "kamle distt.",
    "keyi panyor",
    "kra daadi",
    "kurung kumay",
    "leparada",
    "lohit",
    "longding",
    "lower dibang valley",
    "lower siang",
    "namsai",
    "pakke-kessang distt.",
    "papum pare (city)",
    "papum pare (rural)",
    "shi-yomi",
    "siang",
    "siang east",
    "siang upper",
    "siang west",
    "subansiri lower",
    "subansiri upper",
    "tawang",
    "tirap",
  ],
  assam: [
    "b.i. economic offence",
    "bajali",
    "baksa",
    "barpeta",
    "biswanath",
    "bongaigaon",
    "c i d",
    "cachar",
    "charaideo",
    "chirang",
    "cm's special vigilance",
    "darrang",
    "dhemaji",
    "dhubri",
    "dibrugarh",
    "dima hasao",
    "goalpara",
    "golaghat",
    "govt. rly. police",
    "guwahati central",
    "guwahati crime branch",
    "guwahati east",
    "guwahati west",
    "hailakandi",
    "hojai",
    "jorhat",
    "kamrup",
    "karbianglong",
    "kokrajhar",
    "lakhimpur",
    "majuli",
    "morigaon",
    "nagaon",
    "nalbari",
    "river p s",
    "sadiya",
    "sibsagar",
    "sonitpur",
    "south salmara",
    "special task force",
    "sribhumi",
    "tamulpur",
    "tinsukia",
    "udalguri",
    "vigilance and anti-corruption(v and ac)",
    "west karbi-anglong",
  ],
  bihar: [
    "araria",
    "arwal",
    "aurangabad",
    "bagaha",
    "banka",
    "begusarai",
    "betiah",
    "bhabhua",
    "bhagalpur",
    "bhojpur",
    "buxar",
    "darbhanga",
    "gaya",
    "gopalganj",
    "jamui",
    "jehanabad",
    "katihar",
    "khagaria",
    "kishanganj",
    "lakhi sarai",
    "madhepura",
    "madhubani",
    "mothihari",
    "mujaffarpur",
    "munger",
    "nalanda",
    "naughachhia",
    "nawada",
    "patna",
    "phq",
    "purnea",
    "rly jamalpur",
    "rly katihar",
    "rly mujaffarpur",
    "rly patna",
    "rohtas",
    "saharsa",
    "samastipur",
    "saran",
    "sheikhpura",
    "sheohar",
    "sitamarhi",
    "siwan",
    "supaul",
    "vaishali",
  ],
  chandigarh: ["chandigarh"],
  "dadra and nagar haveli and daman and diu": [
    "dadra ngr haveli",
    "daman dist",
    "diu dist",
  ],
  delhi: [
    "central",
    "crime branch",
    "dwarka",
    "e-district",
    "east",
    "eow",
    "igi airport",
    "metro",
    "new delhi",
    "north",
    "north east",
    "north west",
    "outer district",
    "outer north",
    "railways",
    "rohini",
    "shahdara",
    "south",
    "south west",
    "south-east",
    "special cell(sb)",
    "special police unit for women & children",
    "vigilance",
    "west",
  ],
  goa: ["c i d", "north goa", "south goa"],
  gujarat: [
    "ahmedabad city",
    "ahmedabad rural",
    "ahwa (dangs)",
    "amreli",
    "anand",
    "anti corruption",
    "anti terrorist squad(ats)",
    "arvalli",
    "banaskantha",
    "bharuch",
    "bhavnagar",
    "botad",
    "chhotaudepur",
    "cid crime & railways (cid)",
    "dahod",
    "devbhumi dwarka",
    "gandhinagar",
    "gir somnath",
    "jamnagar",
    "junagadh",
    "kachchh east(gandhidham)",
    "kheda",
    "kutchh/bhuj",
    "mahisagar",
    "mehsana",
    "morbi",
    "narmada",
    "navsari",
    "panchmahals",
    "patan",
    "porbandar",
    "rajkot city",
    "rajkot rural",
    "sabar kantha",
    "smc",
    "surat city",
    "surat rural",
    "surendra nagar",
    "tapi",
    "vadodara city",
    "vadodara rural",
    "valsad",
    "western railway ahmedabad",
    "wstn rly vadodara",
  ],
  "himachal pradesh": [
    "baddi police distt",
    "bilaspur",
    "c i d",
    "chamba",
    "dehra",
    "govt. rly police",
    "hamirpur",
    "kangra",
    "kinnaur",
    "kullu",
    "lahaul & spiti",
    "mandi",
    "police district nurpur",
    "shimla",
    "sirmaur",
    "solan",
    "state vigilance and anti-corruption\u00a0 bureau (sv & acb)",
    "stf, dharamshala zone",
    "stf, mandi zone",
    "stf, parwanoo zone",
    "una",
  ],
  haryana: [
    "ambala",
    "anti corruption bureau, haryana",
    "bhiwani",
    "charki dadri",
    "dabwali",
    "faridabad",
    "fatehabad",
    "grp ambala cantt",
    "gurugram",
    "hansi",
    "haryana state enforcement bureau (hsenb)",
    "haryana state narcotics control bureau,madhuban karnal",
    "hissar",
    "irrigation and power department",
    "jhajjar",
    "jind",
    "kaithal",
    "karnal",
    "kurukshetra",
    "mahendergarh",
    "nuh",
    "palwal",
    "panchkula",
    "panipat",
    "rewari",
    "rohtak",
    "sirsa",
    "sonipat",
    "special task force (stf)",
    "state crime branch",
    "yamuna nagar",
  ],
  "jammu and kashmir": [
    "acb headquarters jammu",
    "acb headquarters kashmir",
    "anantnag",
    "anti corruption",
    "awantipora",
    "bandipora",
    "baramulla",
    "budgam",
    "c b srinagar",
    "c i d",
    "cb jammu",
    "cyber jammu",
    "doda",
    "ganderbal",
    "handwara",
    "jammu",
    "kargil",
    "kathua",
    "kistwar",
    "kulgam",
    "kupwara",
    "leh",
    "pd sopore",
    "poonch",
    "pulwama",
    "railways jammu",
    "railways srinagar",
    "rajouri",
    "ramban",
    "reasi",
    "samba",
    "shopian",
    "sp pc cyber srinagar",
    "srinagar",
    "udhampur",
    "kargil",
    "leh",
  ],
  kerala: [
    "alappuzha",
    "ats",
    "c i d",
    "ernakulam city",
    "ernakulam rural",
    "idukki",
    "kannur city",
    "kannur rural",
    "kasargode",
    "kollam city",
    "kollam rural",
    "kottayam",
    "kozhikode city",
    "kozhikode rural",
    "malappuram",
    "palakkad",
    "pathanamthitta",
    "railway police",
    "thiruvananthapuram city",
    "thiruvananthapuram rural",
    "thrissur city",
    "thrissur rural",
    "wynad",
  ],
  karnataka: [
    "bagalkot",
    "ballari",
    "bangalore city",
    "bangalore rural",
    "belagavi",
    "belagavi city",
    "bidar",
    "c i d",
    "chamarajanagar",
    "chikkabalapura",
    "chikkamangaluru",
    "chitradurga",
    "coastal security police",
    "dakshina kannada",
    "davanagere",
    "dharwad",
    "gadag",
    "hassan",
    "haveri",
    "hubli-dharwad city",
    "kalaburagi",
    "kalaburagi city",
    "karnataka railways",
    "kodagu",
    "kolar",
    "kolar gold fields",
    "koppal",
    "mandya",
    "mangaluru city",
    "mysuru city",
    "mysuru district",
    "raichur",
    "ramanagara",
    "shivamogga",
    "tumakuru",
    "udupi",
    "uttara kannada",
    "vijayanagara",
    "vijayapur",
    "yadagir",
  ],
  lakshadweep: ["lakshadweep"],
  meghalaya: [
    "anti corruption",
    "c i d",
    "east jaintia hills",
    "eastern west khasi hills",
    "garo hills east",
    "garo hills south",
    "garo hills west",
    "khasi hills east",
    "khasi hills west",
    "north garo hills",
    "ri-bhoi",
    "south west garo hills",
    "south west khasi hills",
    "transport dept",
    "west jaintia hills",
  ],
  maharashtra: [
    "ahilyanagar district",
    "akola",
    "amravati city",
    "amravati rural",
    "beed",
    "bhandara",
    "brihan mumbai city",
    "buldhana",
    "chandrapur",
    "chhatrapati sambhajinagar (rural)",
    "chhatrapati sambhajinagar city",
    "cyber unit maharashtra state",
    "dharashiv",
    "dhule",
    "gadchiroli",
    "gondia",
    "hingoli",
    "jalgaon",
    "jalna",
    "kolhapur",
    "latur",
    "mira-bhayandar, vasai-virar police commissioner",
    "nagpur city",
    "nagpur rural",
    "nanded",
    "nandurbar",
    "nashik city",
    "nashik rural",
    "navi mumbai",
    "palghar",
    "parbhani",
    "pimpri-chinchwad police commissionerate",
    "pune city",
    "pune rural",
    "raigad",
    "railway chhatrapati sambhajinagar",
    "railway mumbai",
    "railway nagpur",
    "railway pune",
    "ratnagiri",
    "sangli",
    "satara",
    "sindhudurg",
    "solapur city",
    "solapur rural",
    "state anti terrorist squad",
    "thane city",
    "thane rural",
    "wardha",
    "washim",
    "yavatmal",
  ],
  manipur: [
    "bishnupur",
    "c i d",
    "chandel",
    "churachandpur",
    "imphal east",
    "imphal west",
    "senapati",
    "tamenglong",
    "thoubal",
    "ukhrul",
  ],
  "madhya pradesh": [
    "agar malwa",
    "alirajpur",
    "anuppur",
    "ashoknagar",
    "badwani",
    "baitul",
    "balaghat",
    "bhind",
    "bhopal rural",
    "bhopal urban",
    "burhanpur",
    "chhatarpur",
    "chhindwara",
    "cid",
    "cyber cell",
    "damoh",
    "datia",
    "dewas",
    "dhar",
    "dindori",
    "eow",
    "guna",
    "gwalior",
    "harda",
    "indore rural",
    "indore urban",
    "jabalpur",
    "jhabua",
    "katni",
    "khandwa",
    "khargone",
    "lokayukta",
    "maihar",
    "mandla",
    "mandsaur",
    "mauganj",
    "morena",
    "narcotics",
    "narmadapuram",
    "narsinghpur",
    "neemuch",
    "niwadi",
    "pandhurna",
    "panna",
    "rail bhopal",
    "rail indore",
    "rail jabalpur",
    "raisen",
    "rajgarh",
    "ratlam",
    "rewa",
    "sagar",
    "satna",
    "sehore",
    "seoni",
    "shahdol",
    "shajapur",
    "sheopur",
    "shivpuri",
    "sidhi",
    "singrauli",
    "stf",
    "tikamgarh",
    "ujjain",
    "umariya",
    "vidisha",
  ],
  mizoram: [
    "aizawl",
    "c.i.d/narcotic",
    "champhai",
    "hnahthial",
    "khawzawl",
    "kolasib",
    "lawngtlai",
    "lunglei",
    "mamit",
    "mizoram common",
    "saiha",
    "saitual",
    "serchhip",
  ],
  nagaland: [
    "dimapur",
    "kiphire",
    "kohima",
    "kohima-crime ps",
    "kohima-narcotics ps",
    "longleng",
    "mokokchung",
    "mon",
    "noklak",
    "peren",
    "phek",
    "shamator",
    "state cyber crime",
    "tseminyu",
    "tuensang",
    "wokha",
    "zunheboto",
  ],
  odisha: [
    "angul",
    "balasore",
    "baragarh",
    "berhampur",
    "bhadrak",
    "bolangir",
    "boudh",
    "cid, crime branch bhubaneswar",
    "cid, crime branch cuttack",
    "commissionerate\u00a0police , bhubaneswar - cuttack",
    "cuttack rural",
    "deogarh",
    "dhenkanal",
    "gajapati",
    "ganjam",
    "human right protection cell",
    "jagatsinghpur",
    "jajpur",
    "jharsuguda",
    "kalahandi",
    "kandhamal",
    "kendrapara",
    "keonjhar",
    "khurda",
    "koraput",
    "malkangiri",
    "mayurbhanj",
    "nabarangpur",
    "nayagarh",
    "nuapada",
    "puri",
    "rayagada",
    "rourkela",
    "sambalpur",
    "srp cuttack",
    "srp rourkela",
    "subarnapur",
    "sundargarh",
    "upd, cuttack",
    "upd,bhubaneswar",
  ],
  punjab: [
    "amritsar rural",
    "barnala",
    "batala",
    "bathinda",
    "crime wing",
    "faridkot",
    "fatehgar sahib",
    "fazilka",
    "ferozepur",
    "govt.rly police",
    "gurdaspur",
    "hoshiarpur",
    "intelligence wing (cid)",
    "jalandhar rural",
    "kapurthala",
    "khanna",
    "ludhiana rural",
    "malerkotla",
    "mansa",
    "moga",
    "nri wing",
    "pathankot",
    "patiala",
    "police commissionerate amritsar",
    "police commissionerate jalandhar",
    "police commissionerate ludhiana",
    "punjab state power corporation limited (pspcl)",
    "rupnagar",
    "sangrur",
    "sas nagar",
    "sbs nagar",
    "shri muktsar sahib",
    "stf wing",
    "tarn taran",
    "vigilance bureau",
  ],
  puducherry: ["karaikal", "puducherry"],
  rajasthan: [
    "ajmer",
    "alwar",
    "ats & sog",
    "balotra",
    "banswara",
    "baran",
    "barmer",
    "beawar",
    "bharatpur",
    "bhilwara",
    "bhiwadi",
    "bikaner",
    "bundi",
    "chittorgarh",
    "churu",
    "cid security",
    "dausa",
    "dcp (crime) jodhpur commissionerate",
    "deeg",
    "deputy commissioner of police - crime- jaipur commissionerate",
    "dholpur",
    "didwana-kuchaman",
    "dungarpur",
    "ganga nagar",
    "grp ajmer",
    "grp jodhpur",
    "hanumangargh",
    "jaipur (west)",
    "jaipur city (east)",
    "jaipur city (north)",
    "jaipur city (south)",
    "jaipur metro",
    "jaipur rural",
    "jaisalmer",
    "jalore",
    "jhalawar",
    "jhunjhunu",
    "jodhpur city east",
    "jodhpur city west",
    "jodhpur rural",
    "karauli",
    "khairthal-tijara",
    "kota city",
    "kota rural",
    "kotputli-behror",
    "nagaur",
    "pali",
    "phalodi",
    "pratapgarh",
    "rajsamand",
    "salumbar",
    "sawai madhopur",
    "sikar",
    "sirohi",
    "tonk",
    "udaipur",
  ],
  sikkim: [
    "gangtok district",
    "gyalshing district",
    "mangan district",
    "namchi district",
    "pakyong district",
    "soreng district",
  ],
  "tamil nadu": [
    "adyar",
    "ambattur",
    "anna nagar",
    "anti terrorism squad - i",
    "anti terrorism squad - ii",
    "anti terrorism squad - iii",
    "ariyalur",
    "avadi",
    "avadi city ccb",
    "avadi city pew",
    "avadi city tiw",
    "cbcid - cc wing",
    "cbcid - cyber cell",
    "cbcid - hqrs",
    "cbcid - north",
    "cbcid - ocu",
    "cbcid - sid",
    "cbcid - south",
    "cciw",
    "ccw sp- i",
    "ccw sp- ii",
    "ccw sp- iii",
    "chengalpattu",
    "chennai - ccb",
    "chennai - pew east",
    "chennai - pew north",
    "chennai - pew south",
    "chennai - pew west",
    "chennai- tiw north",
    "chennai- tiw south",
    "coimbatore",
    "coimbatore city",
    "cscid - chennai",
    "cscid - madurai",
    "cscid-coimbatore",
    "cscid-trichy",
    "csgcid nagapattinam",
    "csgcid- ramnad",
    "cuddalore",
    "dharmapuri",
    "dindigul",
    "eow",
    "erode",
    "flower bazaar",
    "grp chennai",
    "grp trichy",
    "idol wing",
    "kallakurichi",
    "kancheepuram",
    "kanyakumari",
    "karur",
    "kilpauk",
    "kolathur",
    "koyambedu",
    "krishnagiri",
    "madhavaram",
    "madurai",
    "madurai city",
    "mayiladuthurai",
    "mylapore",
    "nagapattinam",
    "namakkal",
    "nib - cid",
    "nilgiris",
    "pallikaranai",
    "perambalur",
    "pudukkottai",
    "pulianthope",
    "q-branch cid",
    "ramanathapuram",
    "ranipet",
    "redhills",
    "salem",
    "salem city",
    "sivagangai",
    "st. thomas mount",
    "t nagar",
    "tambaram",
    "tambaram city-ccb",
    "tambaram city-pew",
    "tambaram city-tiw",
    "tenkasi",
    "thanjavur",
    "theni",
    "thirunelveli",
    "thirupathur",
    "thiruvallur",
    "thiruvannamalai",
    "thoothukudi",
    "tiruchirapalli",
    "tirunelveli city",
    "tiruppur",
    "tiruppur city",
    "tiruvarur",
    "trichirapalli city",
    "triplicane",
    "vellore",
    "villupuram",
    "virudhunagar",
    "vpc - cid",
    "washermenpet",
  ],
  tripura: [
    "crime branch tripura",
    "dhalai",
    "gomati",
    "grps tripura",
    "khowai",
    "north",
    "sepahijala",
    "south",
    "unakoti",
    "west",
  ],
  "uttar pradesh": [
    "a.n.t.f.",
    "aco up",
    "aligarh",
    "ambedkar nagar",
    "amethi",
    "amroha",
    "anti power theft",
    "anti terrorist squad(a.t.s.)",
    "auraiya",
    "ayodhya",
    "azamgarh",
    "badaun",
    "baghpat",
    "bahraich",
    "ballia",
    "balrampur",
    "banda",
    "barabanki",
    "bareilly",
    "basti",
    "bhadohi",
    "bijnor",
    "bulandshahar",
    "c.c.h.q",
    "central (commissionerate kanpur nagar)",
    "central gautam budh nagar",
    "chandauli",
    "chitrakoot",
    "city (commissionerate agra)",
    "city (commissionerate ghaziabad)",
    "city (commissionerate prayagraj)",
    "deoria",
    "east (commissionerate agra)",
    "east (commissionerate kanpur nagar)",
    "eow kanpur sector",
    "eow lucknow sector",
    "eow meerut sector",
    "eow varanasi sector",
    "etah",
    "etawah",
    "fatehgarh",
    "fatehpur",
    "firozabad",
    "ganganagar (commissionerate prayagraj)",
    "gautam budh nagar",
    "gautam budh nagar - gr.noida",
    "gautam budh nagar women security",
    "ghazipur",
    "gomati (commissionerate varanasi)",
    "gonda",
    "gorakhpur",
    "grp section agra",
    "agra",

    "grp section gorakhpur",
    "grp section jhansi",
    "grp section lucknow",
    "grp section moradabad",
    "grp section prayagraj",
    "hamirpur",
    "hapur",
    "hardoi",
    "hathras",
    "jalaun",
    "jaunpur",
    "jhansi",
    "kannauj",
    "kanshiram nagar",
    "kashi (commissionerate varanasi)",
    "kaushambi",
    "kheri",
    "kumbh",
    "kushi nagar",
    "lalitpur",
    "lucknow",
    "lucknow central (commissionerate lucknow)",
    "lucknow east (commissionerate lucknow)",
    "lucknow north (commissionerate lucknow)",
    "lucknow south (commissionerate lucknow)",
    "lucknow west (commissionerate lucknow)",
    "mahoba",
    "mahrajganj",
    "mainpuri",
    "mathura",
    "mau",
    "meerut",
    "mirzapur",
    "moradabad",
    "muzaffar nagar",
    "pilibhit",
    "pratapgarh",
    "rae bareli",
    "ramabai nagar",
    "rampur",
    "rural (commissionerate ghaziabad)",
    "saharanpur",
    "sambhal",
    "sant kabeer nagar",
    "shahjahanpur",
    "shamli",

    "ghaziabad",
    "varanasi",
    "shravasti",
    "siddharth nagar",
    "sitapur",
    "sonbhadra",
    "south (commissionerate kanpur nagar)",
    "state s.i.t.",
    "sultanpur",
    "trans hindon (commissionerate ghaziabad)",
    "u.p. vigilance estt.",
    "unnao",
    "varuna (commissionerate varanasi)",
    "west (commissionerate agra",
    "west (commissionerate kanpur nagar)",
    "yamunanagar (commissionerate prayagraj)",
  ],
  "west bengal": [
    "alipurduar",
    "asansol durgapur police commissionerate",
    "bankura",
    "barasat police district",
    "barrackpore police commissionerate",
    "baruipur police district",
    "basirhat police district",
    "bhangar division",
    "bidhannagar police commissionerate",
    "birbhum",
    "bongaon police district",
    "c i d",
    "chandan nagar police commissionerate",
    "cooch behar",
    "dakshin dinajpur",
    "darjeeling",
    "diamond harbour police district",
    "hooghly rural",
    "howrah grp",
    "howrah police commissionerate",
    "howrah rural",
    "islampur police district",
    "jalpaiguri",
    "jangipur police district",
    "jhargram",
    "kalimpong",
    "kharagpur grp",
    "kolkata central division",
    "kolkata east division(ed)",
    "kolkata eastern sub-division",
    "kolkata north and north suburban division",
    "kolkata police cyber hq",
    "kolkata port division",
    "kolkata south division",
    "kolkata south eastern division",
    "kolkata south suburban division",
    "kolkata south west division",
    "krishnanagar police district",
    "malda",
    "murshidabad police district",
    "paschim medinipur",
    "purba bardhaman",
    "purba medinipur",
    "purulia",
    "raiganj police district",
    "ranaghat police district",
    "sealdah grp",
    "siliguri grp",
    "siliguri police commisonerate",
    "sundarban police district",
  ],
  chhattisgarh: [
    "ambikapur (sarguja)",
    "balod",
    "baloda bazar",
    "balrampur",
    "bastar",
    "bemetara",
    "bijapur",
    "bilaspur",
    "dantewada",
    "dhamtari",
    "durg",
    "gariyaband",
    "gaurela-pendra-marwahi",
    "grp raipur",
    "janjgir/champa",
    "jashpur",
    "kabirdham (kawardha)",
    "kanker",
    "khairagarh-chhui khadan-gandai",
    "kondagaon",
    "korba",
    "koriya",
    "mahasamund",
    "manendragarh-chirmiri-bharatpur",
    "mohla-manpur-ambagarh chouki",
    "mungeli",
    "narayanpur",
    "raigarh",
    "raipur",
    "rajnandgaon",
    "sakti",
    "sarangarh-bilaigarh",
    "sukma",
    "surajpur",
  ],
  jharkhand: [
    "ats jh",
    "bokaro",
    "chaibasa",
    "chatra",
    "crime investigation department (cid)",
    "deoghar",
    "dhanbad",
    "dumka",
    "garhwa",
    "giridih",
    "godda",
    "gumla",
    "hazaribagh",
    "jamshedpur",
    "jamtara",
    "khunti",
    "koderma",
    "latehar",
    "lohardaga",
    "pakur",
    "palamau",
    "rail dhanbad",
    "rail jamshedpur",
    "ramgarh",
    "ranchi",
    "sahebganj",
    "saraikela",
    "simdega",
  ],
  uttarakhand: [
    "almora",
    "bageshwar",
    "chamoli",
    "champawat",
    "dehradun",
    "haridwar",
    "nainital",
    "pauri garhwal",
    "pithoragarh",
    "rudraprayag",
    "tehri garhwal",
    "udham singh nagar",
    "uttarkashi",
  ],
  "national investigation agency": ["n.i.a. - hq"],
  telangana: [
    "adilabad",
    "c i d",
    "cyberabad",
    "director_tscsb",
    "grp secunderabad",
    "hyderabad city",
    "hydraa",
    "jagtial",
    "jayashankar(bhupalpally)",
    "jogulamba gadwal",
    "kamareddy",
    "karimnagar",
    "khammam",
    "komaram bheem, asifabad",
    "kothagudem",
    "mahaboobnagar",
    "mahabubabad",
    "medak",
    "mulugu",
    "nagarkurnool",
    "nalgonda",
    "narayanapet",
    "nirmal",
    "nizamabad",
    "rachakonda",
    "rajanna sircilla",
    "ramagundam",
    "sangareddy",
    "siddipet",
    "suryapet",
    "telangana state anti-narcotics bureau (tnsb)",
    "vikarabad",
    "wanaparthy",
    "warangal commissionarate",
    "women safety wing tg",
  ],
  ladakh: ["kargil", "leh"],
  "narcotics control bureau": [
    "agaratgala",
    "ahmedabad",
    "ajmer",
    "amritsar",
    "banglore",
    "bhopal",
    "bhubaneswar",
    "chandigarh",
    "chennai",
    "cochin",
    "dehradun",
    "delhi",
    "delhi(hq)",
    "goa",
    "gorakhpur",
    "guwahati",
    "hyderabad",
    "imphal",
    "indore",
    "itanagar",
    "jaipur",
    "jammu",
    "jodhpur",
    "kolkata",
    "lucknow",
    "madurai",
    "mandi",
    "mandsaur",
    "mumbai",
    "new jalpaiguri",
    "patna",
    "raipur",
    "ranchi",
    "srinagar",
    "vizag",
  ],
  IB: [
    "IB BIHAR",
    "IB RAJASTHAN",
    "IB CHANDIGARH",
    "IB HIMACHAL PRADESH",
    "IB ASSAM",
    "IB TELANGANA",
    "IB ODISHA",
    "IB ANDHRA PRADESH",
    "IB JHARKHAND",
    "IB CHHATTISGARH",
    "IB UTTAR PRADESH",
    "IB TAMIL NADU",
    "IB MADHYA PRADESH",
    "IB KERALA",
    "IB GUJARAT",
    "IB KARNATAKA",
    "IB JAMMU AND KASHMIR",
    "IB ARUNACHAL PRADESH",
    "IB WEST BENGAL",
    "IB NEW DELHI",
    "IB SIKKIM",
  ],
  CBI: [
    "AC-I New Delhi PS",
    "ACB Delhi PS",
    "ACB Lucknow PS",
    "ACB Chandigarh PS",
    "ACB Chennai PS",
    "ACB Mumbai PS",
    "ACB Bhopal PS",
    "ACB Kolkata PS",
    "ACB Jaipur PS",
    "ACB Jodhpur PS",
    "ACB Nagpur PS",
    "ACB Dehradun PS",
    "ACB Jammu PS",
    "ACB Shimla PS",
    "ACB Srinagar PS",
    "ACB Cochin PS",
    "ACB Thiruvananthapuram PS",
    "ACB Hyderabad PS",
    "ACB Visakhapatnam PS",
    "ACB Pune PS",
    "ACB Goa PS",
    "ACB Gandhi Nagar PS",
    "ACB Ghaziabad PS",
    "ACB Madurai PS",
    "ACB Dhanbad PS",
    "ACB Shillong PS",
    "ACB Imphal PS",
    "ACB Jabalpur PS",
    "ACB Chhattisgarh PS",
    "ACB Portblair PS",
    "ACB Bengaluru PS",
    "ACB Patna PS",
    "ACB Ranchi PS",
    "ACB Guwahati PS",
    "ACB Bhubaneshwar PS",
  ],
  NIA: [
    "NIA New Delhi PS",
    "NIA Hyderabad PS",
    "NIA Kerla PS",
    "NIA West Bengal PS",
    "NIA Jammu PS",
    "NIA Mumbai PS",
    "NIA Chandigarh PS",
    "NIA Assam PS",
    "NIA Lucknow PS",
    "NIA Raipur PS",
    "NIA Ranchi PS",
    "NIA Chennai PS",
    "NIA Imphal PS",
    "NIA Bangalore PS",
    "NIA Patna PS",
    "NIA Bhubaneswar PS",
    "NIA Jaipur PS",
    "NIA Bhopal PS",
    "NIA Ahemadabad PS",
  ],
  NCB: [
    "NCB DELHI PS",
    "NCB MUMBAI PS",
    "NCB CHENNAI PS",
    "NCB KOLKATA PS",
    "NCB LUCKNOW PS",
    "NCB JODHPUR PS",
    "NCB AHMEDABAD PS",
    "NCB JAMMU PS",
    "NCB INDORE PS",
    "NCB GUWAHATI PS",
    "NCB PATNA PS",
    "NCB BANGALORE PS",
    "NCB CHANDIGARH PS",
    "NCB BHUBANESHWAR PS",
    "NCB RANCHI PS",
  ],
};
